- name: Copy kubeconfig files to master nodes
  hosts: master
  user: root
  roles:
    - 04_kubeconfig_files/master_kubeconfig

- name: Copy kubeconfig files to worker nodes
  hosts: worker
  user: root
  roles:
    - 04_kubeconfig_files/worker_kubeconfig