- name: install haproxy
  yum:
    name: haproxy
    state: present

- name: copy haproxy file
  copy:
    src: '{{ role_path }}/files/haproxy.cfg'
    dest: '/etc/haproxy/'
    owner: root
    group: root
    mode: 0644

- name: enable and start haproxy
  systemd:
    name: haproxy
    enable: yes
    state: restarted