apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: elastic
  name: elastic
spec:
  containers:
  - image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1 
    name: elastic
    ports:
      - containerPort: 9200
    volumeMounts:
    - name: elasticsearch-config
      mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
      subPath: elasticsearch.yml
    - name: data
      mountPath: "/usr/share/elasticsearch/data"
  restartPolicy: Always
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: elastic-pvc
  - name: elasticsearch-config
    configMap:
      name: es-config
      items:
        - key: elasticsearch.yml
          path: elasticsearch.yml  
