apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1.7Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.50.200
    path: "/mnt/data/jellyfin"
